# Use an official Node.js 14 image as the base image
FROM node:18

# Set the working directory inside the container
WORKDIR /app

COPY . .

RUN cd libs/ckeditor5-classic && npm install && cd ../..

RUN npm install

RUN npm i sharp

# Build your Next.js application (you may need to adjust the build command)
RUN npm run build

# Expose port 80 for the web server
EXPOSE 80

# Start your Next.js application
CMD ["npm", "start"]
