version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nextjs-app
    ports:
      - "80:3000"
    networks:
      - app-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb-prod
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data-prod:/data/db
    # networks:
    #   - app-network

networks:
  app-network:
    driver: bridge
