version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nextjs-app
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
