import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import NextAuthSessionProvider from "@/app/providers/NextAuthSessionProvider"
import ToastifyProvider from "@/app/providers/ToastifyProvider"
import "react-toastify/dist/ReactToastify.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <NextAuthSessionProvider>
        <body className={inter.className}>
          <ToastifyProvider>{children}</ToastifyProvider>
        </body>
      </NextAuthSessionProvider>
    </html>
  )
}
